---
title: "Sub-Task"
output:
  html_document:
    css: ../style.css
    toc: yes
  pdf_document:
    toc: yes
---

```{r warning = FALSE, message = FALSE, echo = FALSE}

source("functions/load.code.R")

```

## Read Fulfiller Data In

```{r warning = FALSE, message = FALSE, echo = TRUE}

f <- read_csv("data-sources/example_data.csv")

```

`r knitr::kable(head(f))` 

## Replicate Data Pull

```{r warning = FALSE, message = FALSE, echo = TRUE}

q <- data.frame(list(Test = "SAT", Year = "2015", N = "1724980"))

```

`r knitr::kable(head(q))` 

## QC Analysis

```{r warning = FALSE, message = FALSE, echo = TRUE}

f <- long(f, 1:2)
q <- as.data.points(q, 1:2)
dp <- data_points(f, q)
datapointsr::match_category_metadata(dp)

# See what a matching version would look like:

dp <- data_points(f, f)
match_values(dp)

```

`r html_matching_report(dp, "QC Match")`

# NOTES

>**NOTE** `f` is fulfiller dataset and `q` is QC analyst dataset.

>**NOTE** This document was created on `r Sys.time()` by `r Sys.getenv("USERNAME")`.

```{r warning = FALSE, message = FALSE, echo = FALSE}

source(sprintf("%s/functions/dispose.code.R",
               dirname(getwd())))

```
